package task2

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"
	"task/v/task2/contract"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
)

// Task2 connects to Sepolia and calls the Counter contract generated by abigen.
func Task2() {
	rpcURL := os.Getenv("SEPOLIA_RPC_URL")
	privateKeyHex := os.Getenv("SEPOLIA_PRIVATE_KEY")
	contractAddrHex := os.Getenv("COUNTER_CONTRACT_ADDRESS")

	if rpcURL == "" || privateKeyHex == "" || contractAddrHex == "" {
		log.Fatal("missing env: SEPOLIA_RPC_URL, SEPOLIA_PRIVATE_KEY, COUNTER_CONTRACT_ADDRESS")
	}

	client, err := ethclient.Dial(rpcURL)
	if err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()
	chainID, err := client.ChainID(ctx)
	if err != nil {
		log.Fatal(err)
	}

	privateKeyHex = strings.TrimPrefix(privateKeyHex, "0x")
	privateKey, err := crypto.HexToECDSA(privateKeyHex)
	if err != nil {
		log.Fatal(err)
	}

	auth, err := bind.NewKeyedTransactorWithChainID(privateKey, chainID)
	if err != nil {
		log.Fatal(err)
	}

	counterAddr := common.HexToAddress(contractAddrHex)
	counter, err := contract.NewCounter(counterAddr, client)
	if err != nil {
		log.Fatal(err)
	}

	tx, err := counter.Increment(auth)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("increment tx: %s\n", tx.Hash().Hex())

	count, err := counter.Count(&bind.CallOpts{Context: ctx})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("count: %s\n", count.String())
}
